Document: botcommander
Title: Debian botcommander Manual
Author: Gergely POLONKAI (polesz@botcommander.hu)
Abstract: This manual describes what botcommander is
 and how it can be used to
 manage online manuals on Debian systems.
Section: utils

Format: debiandoc-sgml
Files: /usr/share/doc/botcommander/botcommander.sgml.gz

Format: postscript
Files: /usr/share/doc/botcommander/botcommander.ps.gz

Format: text
Files: /usr/share/doc/botcommander/botcommander.text.gz

Format: HTML
Index: /usr/share/doc/botcommander/html/index.html
Files: /usr/share/doc/botcommander/html/*.html

  
